### ISSUE TITLE
try to use std library for use case

### ISSUE THREAD

**Issue by mhf-ir** [slashmili/php-gd-persian#3]
Why not using fribidi ?
https://github.com/fribidi/fribidi
https://pecl.php.net/package/fribidi

**Comment by slashmili** [comment]
@mhf-ir Sure whatever works the best, otherwise:
* If some people can not install `fribidi` pecl, they can use this library
* For my own case, I had to feed an existing application that used usual image function. 

I should mention the code in the repo was pushed [13 years ago](https://github.com/slashmili/php-gd-persian/commit/d8550184d142e67ae290fc5964bbb41d7dba137d) and not sure if it works, so if you have to use it, use it with grace 🤷‍♂
